### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by xcloudx01** [Bortugini/DNS_Speed_Test_Tool#1]
The error is:
File konte nicht geöffnet werden.
Traceback (most recent call last):
  File "D:\Downloaded Repos\DNS_Speed_Test_Tool\DNS_Speed_Test_Tool.py", line 80, in <module>
    for i in range(len(ip)):
TypeError: object of type 'NoneType' has no len()

**Comment by xcloudx01** [comment]
I fixed it by changing "DNS Servers.txt" to "DNS Server.txt" in the DNS_Speed_Test_Tool.py file.

However, this new error occurs: [https://pastebin.com/BTr074Fi](https://pastebin.com/BTr074Fi)

**Comment by Bortugini** [comment]
Hello, 
I think the problem is that your computer is set to English and I use German.
You can change lines 24, 27, 34 to your language, that should fix the problem.

**Comment by xcloudx01** [comment]
Awesome, thanks! I'll fix it for my English system and make a pull request
